# Basic
title: 青鸾峰
subtitle: 浮云千载、唯忆君颜
welcome_message: 欢迎来到我的起点
description: 搬运了<a href='http://onev.cat'>喵神@onevcat</a>博客的构筑，自己正在前端路上匍匐前进
creator: <a href="https://mikasaackerman.github.io">maomao</a>

url: "https://mikasaackerman.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

blog_button:
    title: 博客
    description: 访问博客

nav:
   

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: maomao-1
    # duoshuo:
# Social
social:
    weibo: 1696225282
    github: MikasaAckerman
    twitter: maomaonott
    mail: maomaonoyh@yahoo.co.jp

# Google Analytics
ga:
    id: 
    host: 
